version: '3.1'

services:
  db:
    container_name: ${NAME}-db
    image: pgautoupgrade/pgautoupgrade:17-debian
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=dea
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
  solr:
    container_name: ${NAME}-solr
    build: solr-docker
    restart: unless-stopped
    volumes:
      - ${SOLR_DATA}:/var/solr/data
    ports:
      - ${SOLR_HTTP}:8983
  dea:
    container_name: ${NAME}-app
    build: ./
    restart: unless-stopped
    environment:
      - APP_CONTEXT=${APP_CONTEXT}
      - JDBC_NAME=${DB_USER}
      - JDBC_PASSWORD=${DB_PASSWORD}
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_URL=jdbc:postgresql://db:5432/dea
      - SOLR_URL=http://solr:8983
      - SOLR_CORE=dea
      - SOLR_CLASSIFICATION_CORE=dea-classifications
      - XMX=${APP_XMX}
      - XMS=${APP_XMS}
      - APP_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8295
    volumes:
      - ${APP_HOME}:/mcr/home/
      - ${APP_DATA}:/mcr/data/
      - ${APP_LOGS}:/mcr/logs/
      - ${APP_TMP}:/mcr/tmp/
      - ./:/mcr/dev/
    depends_on:
      - db
      - solr
    ports:
      - ${APP_HTTP}:8080
      - ${APP_AJP}:8009
      - ${APP_DEBUG}:8295
