
name: docker container deploy
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Maven
        run: mvn --batch-mode package
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the dea Docker images and push them
        if: success()
        run: |
          docker build . --file Dockerfile --tag vzgreposis/digital-edition-archive:${GITHUB_REF_NAME}
          docker build solr-docker --file solr-docker/Dockerfile --tag vzgreposis/digital-edition-archive-solr:${GITHUB_REF_NAME}
          docker push vzgreposis/digital-edition-archive:${GITHUB_REF_NAME}
          docker push vzgreposis/digital-edition-archive-solr:${GITHUB_REF_NAME}    
