# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Snapshot deploy

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Publish to OSSRH with Apache Maven
        run: mvn --batch-mode package
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the mir Docker images and push them
        if: success()
        run: |
          docker build . --file Dockerfile --tag vzgreposis/digital-edition-archive:${GITHUB_REF_NAME}
          docker build solr-docker --file solr-docker/Dockerfile --tag vzgreposis/digital-edition-archive-solr:${GITHUB_REF_NAME}
          docker push vzgreposis/digital-edition-archive:${GITHUB_REF_NAME}
          docker push vzgreposis/digital-edition-archive-solr:${GITHUB_REF_NAME}    
